// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: support.proto

package support

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageText   string                 `protobuf:"bytes,1,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_support_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_support_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_support_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

func (x *ClassifyRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type ClassifyResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Category          string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Confidence        float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ExtractedEntities map[string]string      `protobuf:"bytes,3,rep,name=extracted_entities,json=extractedEntities,proto3" json:"extracted_entities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_support_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_support_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_support_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ClassifyResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassifyResponse) GetExtractedEntities() map[string]string {
	if x != nil {
		return x.ExtractedEntities
	}
	return nil
}

type GenerateReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageText   string                 `protobuf:"bytes,1,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReplyRequest) Reset() {
	*x = GenerateReplyRequest{}
	mi := &file_support_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReplyRequest) ProtoMessage() {}

func (x *GenerateReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_support_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReplyRequest.ProtoReflect.Descriptor instead.
func (*GenerateReplyRequest) Descriptor() ([]byte, []int) {
	return file_support_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateReplyRequest) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

func (x *GenerateReplyRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *GenerateReplyRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GenerateReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyText     string                 `protobuf:"bytes,1,opt,name=reply_text,json=replyText,proto3" json:"reply_text,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	RequiresHuman bool                   `protobuf:"varint,3,opt,name=requires_human,json=requiresHuman,proto3" json:"requires_human,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReplyResponse) Reset() {
	*x = GenerateReplyResponse{}
	mi := &file_support_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReplyResponse) ProtoMessage() {}

func (x *GenerateReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_support_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReplyResponse.ProtoReflect.Descriptor instead.
func (*GenerateReplyResponse) Descriptor() ([]byte, []int) {
	return file_support_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateReplyResponse) GetReplyText() string {
	if x != nil {
		return x.ReplyText
	}
	return ""
}

func (x *GenerateReplyResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *GenerateReplyResponse) GetRequiresHuman() bool {
	if x != nil {
		return x.RequiresHuman
	}
	return false
}

var File_support_proto protoreflect.FileDescriptor

const file_support_proto_rawDesc = "" +
	"\n" +
	"\rsupport.proto\x12\asupport\"Q\n" +
	"\x0fClassifyRequest\x12!\n" +
	"\fmessage_text\x18\x01 \x01(\tR\vmessageText\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\"\xf5\x01\n" +
	"\x10ClassifyResponse\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12_\n" +
	"\x12extracted_entities\x18\x03 \x03(\v20.support.ClassifyResponse.ExtractedEntitiesEntryR\x11extractedEntities\x1aD\n" +
	"\x16ExtractedEntitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x14GenerateReplyRequest\x12!\n" +
	"\fmessage_text\x18\x01 \x01(\tR\vmessageText\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"}\n" +
	"\x15GenerateReplyResponse\x12\x1d\n" +
	"\n" +
	"reply_text\x18\x01 \x01(\tR\treplyText\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12%\n" +
	"\x0erequires_human\x18\x03 \x01(\bR\rrequiresHuman2\xa3\x01\n" +
	"\tAIService\x12F\n" +
	"\x0fClassifyMessage\x12\x18.support.ClassifyRequest\x1a\x19.support.ClassifyResponse\x12N\n" +
	"\rGenerateReply\x12\x1d.support.GenerateReplyRequest\x1a\x1e.support.GenerateReplyResponseBCZAgithub.com/Konstantin-Korolyov/go-support-assistant/proto/supportb\x06proto3"

var (
	file_support_proto_rawDescOnce sync.Once
	file_support_proto_rawDescData []byte
)

func file_support_proto_rawDescGZIP() []byte {
	file_support_proto_rawDescOnce.Do(func() {
		file_support_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_support_proto_rawDesc), len(file_support_proto_rawDesc)))
	})
	return file_support_proto_rawDescData
}

var file_support_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_support_proto_goTypes = []any{
	(*ClassifyRequest)(nil),       // 0: support.ClassifyRequest
	(*ClassifyResponse)(nil),      // 1: support.ClassifyResponse
	(*GenerateReplyRequest)(nil),  // 2: support.GenerateReplyRequest
	(*GenerateReplyResponse)(nil), // 3: support.GenerateReplyResponse
	nil,                           // 4: support.ClassifyResponse.ExtractedEntitiesEntry
}
var file_support_proto_depIdxs = []int32{
	4, // 0: support.ClassifyResponse.extracted_entities:type_name -> support.ClassifyResponse.ExtractedEntitiesEntry
	0, // 1: support.AIService.ClassifyMessage:input_type -> support.ClassifyRequest
	2, // 2: support.AIService.GenerateReply:input_type -> support.GenerateReplyRequest
	1, // 3: support.AIService.ClassifyMessage:output_type -> support.ClassifyResponse
	3, // 4: support.AIService.GenerateReply:output_type -> support.GenerateReplyResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_support_proto_init() }
func file_support_proto_init() {
	if File_support_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_support_proto_rawDesc), len(file_support_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_support_proto_goTypes,
		DependencyIndexes: file_support_proto_depIdxs,
		MessageInfos:      file_support_proto_msgTypes,
	}.Build()
	File_support_proto = out.File
	file_support_proto_goTypes = nil
	file_support_proto_depIdxs = nil
}
